# Generated by Django 5.1.1 on 2025-02-25 18:49

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=50)),
                ('sede', models.CharField(choices=[('jose_marti', 'José Martí'), ('ignacio_agramonte', 'Ignacio Agramonte')], default='', max_length=50)),
                ('disponible', models.BooleanField(default=True)),
                ('capacidad', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Moderator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator])),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Administrador'), ('user', 'Usuario')], default='user', max_length=10)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'app_customuser',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vcName', models.CharField(max_length=150, validators=[django.core.validators.RegexValidator('^[a-zA-Z\\s]*$', 'El nombre solo puede contener letras y espacios.')], verbose_name='Nombre de la Videoconferencia')),
                ('vcMotive', models.CharField(choices=[('mes', 'MES'), ('defdoc', 'Defensa de Doctorado'), ('defmaest', 'Defensa de Maestría'), ('colint', 'Colaboración Internacional'), ('proycoop', 'Proyecto de Cooperación'), ('acred', 'Acreditación'), ('post', 'Posgrado')], default='post', max_length=50, verbose_name='Motivo')),
                ('requestArea', models.CharField(choices=[('cum', 'CUM'), ('fac', 'Facultad'), ('dir', 'Dirección'), ('dir_gen', 'Dirección General'), ('vi', 'Vicerrectoría'), ('re', 'Rectoría')], default='fac', max_length=10, verbose_name='Área de Solicitud')),
                ('url', models.URLField(verbose_name='URL')),
                ('platafom', models.CharField(choices=[('jitsi', 'Jitsi'), ('googlemeet', 'Google Meet'), ('microteams', 'Microsoft Teams')], default='googlemeet', max_length=10, verbose_name='Plataforma')),
                ('weCreators', models.BooleanField(choices=[(True, 'Sí'), (False, 'No')], default=False, verbose_name='¿Somos Creadores?')),
                ('dateTime', models.DateTimeField(verbose_name='Fecha y Hora')),
                ('duration', models.PositiveSmallIntegerField(default=0, verbose_name='Duración')),
                ('cantpart', models.PositiveSmallIntegerField(default=0, verbose_name='Cantidad de Participantes')),
                ('observations', models.TextField(blank=True, verbose_name='Observaciones')),
                ('local', models.CharField(blank=True, max_length=50, null=True, verbose_name='Localización')),
                ('idofModerator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.moderator', verbose_name='Moderador')),
            ],
        ),
    ]
