# Generated by Django 5.1.1 on 2025-02-27 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_reserve_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve',
            name='google_calendar_event_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
