# Generated by Django 5.1.1 on 2025-02-28 03:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_reserve_google_calendar_event_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='disponible',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='moderator',
            name='email',
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
