# Generated by Django 5.1.1 on 2025-02-28 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_local_disponible_alter_moderator_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='duration',
            field=models.PositiveIntegerField(default=0, verbose_name='Duración'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='local',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Local'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(default='light', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
