# Generated by Django 5.1.1 on 2025-03-01 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_local_disponible_alter_reserve_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='google_calendar_event_id',
            field=models.CharField(blank=True, help_text='Se completa automáticamente al sincronizar', max_length=255, null=True, verbose_name='ID de Evento en Google Calendar'),
        ),
    ]
