# Generated by Django 5.1.1 on 2025-04-22 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_reserve_google_calendar_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve',
            name='rejection_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reserve',
            name='rejection_reason',
            field=models.CharField(blank=True, choices=[('schedule', 'Solapamiento de horario'), ('capacity', 'Capacidad excedida'), ('moderator', 'Moderador no disponible'), ('other', 'Otro motivo')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='reserve',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('rejected', 'Rechazado')], default='pending', max_length=10),
        ),
    ]
