# Generated by Django 5.1.1 on 2025-04-23 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_reserve_rejection_details_reserve_rejection_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='rejection_details',
            field=models.TextField(blank=True, null=True, verbose_name='Detalles del rechazo'),
        ),
    ]
