# Generated by Django 5.1.1 on 2025-04-24 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve',
            name='status_anterior',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
